trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: UnityGetProjectVersionTask@1
  name: unitygetprojectversion
  inputs:
    unityProjectPath: 'TheMostAwesomeGameEverMade/'

- task: UnitySetupTask@1
  inputs:
    versionSelectionMode: 'specify'
    version: '$(unitygetprojectversion.projectVersion)'
    revision: '$(unitygetprojectversion.projectVersionRevision)'
    installWindowsIL2CPPModule: true

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'standalone'
    unityProjectPath: 'TheMostAwesomeGameEverMade/'
    versionSelectionMode: 'project'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'TheMostAwesomeGameEverMade'

# Copy build output files to artifact staging directory.
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.BinariesDirectory)
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    CleanTargetFolder: true
    OverWrite: true

# Finally publish all items in artifact staging to the Azure Pipelines
# artifact storage. They will be available for sharing and/or further processing there.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    publishLocation: Container